# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbecfe505488bcd2484dea5373ac1aadde448f762775f6d7f952315eae9de0e0e2a5c6ae6817e4cd12136fef1318a205a8dd8ee86fe306d8682e84aaaa81742f

test:
  secret_key_base: 8786ed5d7527d8365b75389ad4feda580da25e34bdfed4292afe6983d3af576faa4b5b8ac7eb674a9ef4e8d41e28beb2ba50a3a00cf06fac06bbde6efa14bed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
